# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 596)
        MainWindow.setMinimumSize(QtCore.QSize(756, 596))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    color:#000;\n"
"}\n"
"#leftMenu{\n"
"    background-color:#2596be;\n"
"}\n"
"#centralwidget{\n"
"    background-color:#eff9fe;\n"
"}\n"
"#modelListWidget{\n"
"    border : 2px solid #2596be;\n"
"}\n"
"#menuLabel, #modelLabel{\n"
"    font-size:15px;\n"
"}\n"
"#menuTitleLabel{\n"
"    font-size:20px;\n"
"    font-weight : bold;\n"
"}\n"
"#analysisBtn, #modelConfigBtn{\n"
"    background-color : transparent;\n"
"}\n"
"#tab,#tab_2{\n"
"    background-color : #eff9fe;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuTitleFrame = QtWidgets.QFrame(self.leftMenu)
        self.menuTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuTitleFrame.setObjectName("menuTitleFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menuTitleFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menuTitleLabel = QtWidgets.QLabel(self.menuTitleFrame)
        self.menuTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.menuTitleLabel.setObjectName("menuTitleLabel")
        self.verticalLayout_3.addWidget(self.menuTitleLabel, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.menuTitleFrame)
        self.subMenuWidget = QtWidgets.QWidget(self.leftMenu)
        self.subMenuWidget.setObjectName("subMenuWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.subMenuWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.analysisBtn = QtWidgets.QPushButton(self.subMenuWidget)
        self.analysisBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.analysisBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/message-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analysisBtn.setIcon(icon)
        self.analysisBtn.setObjectName("analysisBtn")
        self.verticalLayout_4.addWidget(self.analysisBtn)
        self.modelConfigBtn = QtWidgets.QPushButton(self.subMenuWidget)
        self.modelConfigBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.modelConfigBtn.setStyleSheet("background-color: #2596be;\n"
"border: 2px solid white;\n"
"border-radius: 20px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modelConfigBtn.setIcon(icon1)
        self.modelConfigBtn.setObjectName("modelConfigBtn")
        self.verticalLayout_4.addWidget(self.modelConfigBtn)
        self.verticalLayout.addWidget(self.subMenuWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.leftMenu)
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        self.mainBody.setObjectName("mainBody")
        self.gridLayout = QtWidgets.QGridLayout(self.mainBody)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.headerFrame = QtWidgets.QWidget(self.mainBody)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuWidget = QtWidgets.QWidget(self.headerFrame)
        self.menuWidget.setMinimumSize(QtCore.QSize(0, 70))
        self.menuWidget.setMaximumSize(QtCore.QSize(50, 70))
        self.menuWidget.setObjectName("menuWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menuWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuBtn = QtWidgets.QPushButton(self.menuWidget)
        self.menuBtn.setMaximumSize(QtCore.QSize(45, 41))
        self.menuBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/blueIcons/blueIcons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon2)
        self.menuBtn.setIconSize(QtCore.QSize(32, 32))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_3.addWidget(self.menuBtn, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.menuWidget)
        self.modelWidget = QtWidgets.QWidget(self.headerFrame)
        self.modelWidget.setMinimumSize(QtCore.QSize(0, 70))
        self.modelWidget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.modelWidget.setObjectName("modelWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.modelWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.modelLabel = QtWidgets.QLabel(self.modelWidget)
        self.modelLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.modelLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.modelLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.modelLabel.setObjectName("modelLabel")
        self.horizontalLayout_4.addWidget(self.modelLabel)
        self.modelComboBox = QtWidgets.QComboBox(self.modelWidget)
        self.modelComboBox.setMinimumSize(QtCore.QSize(0, 41))
        self.modelComboBox.setObjectName("modelComboBox")
        self.horizontalLayout_4.addWidget(self.modelComboBox)
        self.horizontalLayout_2.addWidget(self.modelWidget)
        self.gridLayout.addWidget(self.headerFrame, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.mainBody)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainFrame = QtWidgets.QWidget(self.tab)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkFrame = QtWidgets.QGroupBox(self.mainFrame)
        self.checkFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.checkFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkFrame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.checkFrame.setObjectName("checkFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.checkFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(self.checkFrame)
        self.checkBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.checkFrame)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.checkFrame)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.verticalLayout_2.addWidget(self.checkFrame)
        self.questionFrame = QtWidgets.QFrame(self.mainFrame)
        self.questionFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.questionFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.questionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.questionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questionFrame.setObjectName("questionFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.questionFrame)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        # self.quesionTextEdit = QtWidgets.QTextEdit(self.questionFrame)
        # self.quesionTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        # self.quesionTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        # self.quesionTextEdit.setObjectName("quesionTextEdit")
        # self.horizontalLayout_5.addWidget(self.quesionTextEdit)
        # self.submitBtn = QtWidgets.QPushButton(self.questionFrame)
        # self.submitBtn.setMinimumSize(QtCore.QSize(0, 40))
        # self.submitBtn.setMaximumSize(QtCore.QSize(16777215, 40))
        # self.submitBtn.setText("")
        # icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap(":/blueIcons/blueIcons/navigation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.submitBtn.setIcon(icon3)
        # self.submitBtn.setIconSize(QtCore.QSize(32, 32))
        # self.submitBtn.setObjectName("submitBtn")
        # self.horizontalLayout_5.addWidget(self.submitBtn)
        self.verticalLayout_2.addWidget(self.questionFrame)
        self.answerFrame = QtWidgets.QFrame(self.mainFrame)
        self.answerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answerFrame.setObjectName("answerFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.answerFrame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.answerFrame)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.answerFrame)
        self.progressBar = QtWidgets.QProgressBar(self.mainFrame)
        self.progressBar.setStyleSheet("text-align : center;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_5.addWidget(self.mainFrame)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.mainBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuTitleLabel.setText(_translate("MainWindow", "언어 순화 프로그램"))
        self.analysisBtn.setText(_translate("MainWindow", "텍스트 분석"))
        self.modelConfigBtn.setText(_translate("MainWindow", "모델 설정"))
        self.modelLabel.setText(_translate("MainWindow", "모델 선택"))
        self.checkFrame.setTitle(_translate("MainWindow", "순화 대상"))
        self.checkBox_1.setText(_translate("MainWindow", "욕설·비속어"))
        self.checkBox_2.setText(_translate("MainWindow", "외래어"))
        self.checkBox_3.setText(_translate("MainWindow", "은어"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
